-- Insert a sample test question with diagram_json for Test Series 1
INSERT INTO test_questions (
  course_id,
  unit_id,
  test_name,
  question_statement,
  question_type,
  options,
  answer,
  correct_marks,
  incorrect_marks,
  partial_marks,
  skipped_marks,
  time_minutes,
  solution,
  diagram_json
) VALUES (
  '660e8400-e29b-41d4-a716-446655440001',
  '880e8400-e29b-41d4-a716-446655440002',
  'Test Series 1',
  'The 15 parts of the given figure are to be painted such that no two adjacent parts (excluding corners) have the same color. The minimum number of colors required is:',
  'MCQ',
  '["4", "3", "5", "6"]'::jsonb,
  '3',
  4,
  -1,
  1,
  0,
  2,
  'This is a graph coloring problem. The figure can be divided into 15 regions. By analyzing the adjacency relationships, we need to find the chromatic number. The minimum number of colors required to paint the figure such that no two adjacent regions have the same color is 3. This can be proven by: 1) Showing that 3 colors are sufficient by providing a valid coloring, 2) Proving that 2 colors are not sufficient by identifying an odd cycle or other structure requiring at least 3 colors.',
  '[
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 1,
      "isDeleted": false,
      "id": "outer-ellipse",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 100,
      "y": 80,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 400,
      "height": 280,
      "seed": 1,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false
    },
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 2,
      "isDeleted": false,
      "id": "inner-ellipse",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 180,
      "y": 140,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 240,
      "height": 160,
      "seed": 2,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false
    },
    {
      "type": "rectangle",
      "version": 1,
      "versionNonce": 3,
      "isDeleted": false,
      "id": "center-square",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 230,
      "y": 170,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 140,
      "height": 100,
      "seed": 3,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false
    },
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 4,
      "isDeleted": false,
      "id": "center-circle",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 260,
      "y": 190,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 80,
      "height": 60,
      "seed": 4,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false
    },
    {
      "type": "line",
      "version": 1,
      "versionNonce": 5,
      "isDeleted": false,
      "id": "line-1",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 300,
      "y": 80,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 0,
      "height": 140,
      "seed": 5,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false,
      "startBinding": null,
      "endBinding": null,
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [[0, 0], [0, 140]]
    },
    {
      "type": "line",
      "version": 1,
      "versionNonce": 6,
      "isDeleted": false,
      "id": "line-2",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 300,
      "y": 300,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 0,
      "height": 60,
      "seed": 6,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false,
      "startBinding": null,
      "endBinding": null,
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [[0, 0], [0, 60]]
    },
    {
      "type": "line",
      "version": 1,
      "versionNonce": 7,
      "isDeleted": false,
      "id": "line-3",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 260,
      "y": 220,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 80,
      "height": 0,
      "seed": 7,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false,
      "startBinding": null,
      "endBinding": null,
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [[0, 0], [80, 0]]
    },
    {
      "type": "line",
      "version": 1,
      "versionNonce": 8,
      "isDeleted": false,
      "id": "line-4",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 230,
      "y": 220,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 140,
      "height": 0,
      "seed": 8,
      "groupIds": [],
      "frameId": null,
      "roundness": null,
      "boundElements": [],
      "updated": 1,
      "link": null,
      "locked": false,
      "startBinding": null,
      "endBinding": null,
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [[0, 0], [140, 0]]
    }
  ]'::jsonb
);