// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvcaoionosquiimjffpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2Y2FvaW9ub3NxdWlpbWpmZnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTg4NzUsImV4cCI6MjA2OTE5NDg3NX0.jL5kUuBUD_XXVlamKDn_jGQMPk6ceaoL2ux4VpUe3Qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});