
-- First, insert ISI exam if it doesn't exist
INSERT INTO public.exams (
  id,
  name,
  description,
  short_description,
  detailed_description,
  introduction,
  history,
  rankings,
  infrastructure,
  placements,
  fees_scholarships,
  preparation_tips,
  why_choose,
  image_url,
  established_year,
  location,
  campuses,
  recognition,
  global_collaborations,
  faqs
) VALUES (
  gen_random_uuid(),
  'ISI',
  'Indian Statistical Institute - Premier institute for Statistics, Mathematics & Data Science',
  'Premier institute for Statistics, Mathematics & Data Science',
  'Indian Statistical Institute (ISI) is one of India''s most prestigious institutions for advanced studies in Statistics, Mathematics, Data Science, Economics, and Computer Science. Established in 1931, ISI has been at the forefront of statistical research and education for over 90 years.',
  'ISI Kolkata stands as a beacon of excellence in quantitative sciences, consistently ranked among the top institutions globally for research in statistics and mathematics. The institute has produced numerous Nobel laureates, statisticians, and data scientists who have made significant contributions to their fields.',
  'Founded in 1931 by Professor Prasanta Chandra Mahalanobis, often called the "Father of Indian Statistics," ISI began as a small research institute and has grown into a world-renowned center of excellence. Mahalanobis established ISI with the vision of developing statistical methods for planning and development in India. The institute played a crucial role in India''s Five-Year Plans and continues to contribute to policy-making through statistical research.',
  'ISI is consistently ranked #1 in Statistics in India and among the top 10 globally in statistical research publications. It holds the prestigious Institute of National Importance status granted by the Government of India. The institute has received NAAC A++ grade and is recognized by UGC. ISI faculty and alumni have received numerous international awards including Fields Medal considerations and prestigious fellowships.',
  'ISI boasts world-class infrastructure including a library with over 2 lakh books and journals, one of the largest collections in Asia for statistics and mathematics. The institute has high-performance computing facilities, advanced research laboratories, and state-of-the-art classrooms. Students enjoy subsidized hostel accommodation with modern amenities, sports facilities, and recreational areas.',
  'ISI graduates command some of the highest packages in the industry with average packages ranging from ₹15-25 LPA across programs. Top recruiters include Goldman Sachs, JP Morgan Chase, Amazon, Microsoft, Google, Facebook, McKinsey & Company, Boston Consulting Group, and leading research institutions worldwide. The alumni network spans across top global firms and academic institutions.',
  'ISI offers education at almost zero cost with most programs having minimal tuition fees (₹2,000-₹40,000 total). All students receive monthly stipends ranging from ₹8,000 to ₹12,000. Merit-based scholarships and government fellowships are available for PhD students. The institute also provides financial assistance for conference participation and research activities.',
  'Success at ISI requires strong mathematical foundations and analytical thinking. Focus on building expertise in linear algebra, calculus, probability theory, and statistical inference. Practice extensively with previous year papers as ISI maintains consistent exam patterns. Develop problem-solving skills through regular practice of challenging mathematical problems. Join study groups and seek guidance from current students or faculty.',
  'ISI offers a unique combination of rigorous academics, research opportunities, and excellent career prospects. The institute provides free world-class education with stipends, ensuring financial accessibility. Students gain exposure to cutting-edge research and have opportunities to work with renowned faculty. The small batch sizes ensure personalized attention and strong peer relationships that last a lifetime.',
  '/images/isi-kolkata.jpg',
  1931,
  'Kolkata, West Bengal',
  ARRAY['Kolkata (Main Campus)', 'Delhi', 'Bangalore', 'Chennai', 'Tezpur', 'Hyderabad'],
  'Institute of National Importance, NAAC A++ Grade, UGC Recognition, ISO 9001:2015 Certified',
  'ISI has extensive partnerships with Harvard University, MIT, Stanford University, Oxford University, Cambridge University, and other leading institutions worldwide for research collaborations, student exchange programs, and joint degree offerings.',
  '[
    {"question": "Is ISI better than IITs for Data Science and Statistics?", "answer": "ISI offers specialized programs with deeper focus on theoretical foundations of statistics and mathematics, while IITs offer broader engineering-based data science programs. For pure statistics and research, ISI is unmatched."},
    {"question": "Does ISI provide hostel facilities for all students?", "answer": "Yes, ISI provides subsidized hostel accommodation for all students with separate facilities for boys and girls. The hostels are well-maintained with modern amenities."},
    {"question": "How difficult is the ISI admission test compared to JEE?", "answer": "The ISI entrance exam is conceptually challenging and requires deep understanding rather than speed. It focuses more on mathematical maturity and analytical thinking compared to JEE."},
    {"question": "Do all students get stipends at ISI?", "answer": "Yes, all admitted students receive monthly stipends. The amount varies by program but typically ranges from ₹8,000 to ₹12,000 per month."},
    {"question": "What are the career prospects after ISI?", "answer": "ISI graduates have excellent career prospects in academia, research, finance, technology, and consulting. Many pursue PhD programs at top global universities or join leading firms with attractive packages."},
    {"question": "Can students from non-mathematics backgrounds apply to ISI?", "answer": "Yes, several programs accept students from diverse backgrounds. However, strong mathematical aptitude is essential for success in all ISI programs."}
  ]'::jsonb
) ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  detailed_description = EXCLUDED.detailed_description,
  introduction = EXCLUDED.introduction,
  history = EXCLUDED.history,
  rankings = EXCLUDED.rankings,
  infrastructure = EXCLUDED.infrastructure,
  placements = EXCLUDED.placements,
  fees_scholarships = EXCLUDED.fees_scholarships,
  preparation_tips = EXCLUDED.preparation_tips,
  why_choose = EXCLUDED.why_choose,
  image_url = EXCLUDED.image_url,
  established_year = EXCLUDED.established_year,
  location = EXCLUDED.location,
  campuses = EXCLUDED.campuses,
  recognition = EXCLUDED.recognition,
  global_collaborations = EXCLUDED.global_collaborations,
  faqs = EXCLUDED.faqs;

-- Insert MSQMS course for ISI
INSERT INTO public.courses (
  id,
  exam_id,
  name,
  description,
  eligibility,
  duration,
  course_type,
  entrance_exam,
  exam_pattern,
  cutoff_trends,
  intake_capacity,
  fees_amount,
  stipend_amount,
  average_package,
  highest_package,
  top_recruiters,
  software_exposure,
  preparation_strategy,
  detailed_content,
  curriculum,
  course_faqs,
  course_image_url,
  freemium_group,
  premium_group
) VALUES (
  gen_random_uuid(),
  (SELECT id FROM exams WHERE name = 'ISI'),
  'Master of Science in Quality Management Science (MSQMS)',
  'A unique 2-year program combining Statistics, Operations Research, and Quality Management',
  'Bachelor''s degree with Mathematics as a subject OR BE/B.Tech in any discipline with strong mathematical background. Minimum 60% marks in qualifying degree.',
  '2 Years (4 Semesters)',
  'Full-time residential program with dual-campus experience',
  'ISI Admission Test (Common for all ISI programs)',
  'Part A (MCQ - 2 hours): General aptitude (25%), Quantitative aptitude (35%), Basic probability & statistics (40%). Part B (Descriptive - 2 hours): Applied Statistics (30%), Probability distributions (25%), Linear Algebra (25%), Optimization techniques (20%)',
  'General Category: 45-55 marks out of 100, OBC/EWS: 40-50 marks, SC/ST: 30-40 marks. Cutoffs vary annually based on difficulty and competition.',
  15,
  '₹40,000 total program fee + ₹200-400/month hostel charges + ₹1,200-1,500/fortnight mess charges',
  '₹8,000 per month for all students',
  '₹7-10 LPA',
  '₹15 LPA',
  ARRAY['TCS', 'Infosys', 'Boeing', 'Amazon', 'Goldman Sachs', 'JP Morgan', 'Microsoft', 'KPMG', 'Deloitte', 'PwC', 'EY', 'Accenture'],
  ARRAY['Python', 'R', 'SAS', 'MATLAB', 'Minitab', 'LINGO', 'Excel', 'SQL', 'Tableau', 'Power BI'],
  'Build strong foundations in mathematics, statistics, and probability. Practice ISI previous year papers extensively. Develop analytical and problem-solving skills. Focus on quality management concepts and operations research fundamentals. Join online communities and practice groups for better preparation.',
  'The Master of Science in Quality Management Science (MSQMS) is ISI''s flagship interdisciplinary program that uniquely combines statistical methods, operations research techniques, and quality management principles. This program is designed to create industry-ready professionals who can apply statistical thinking to solve complex business problems. Students experience a dual-campus journey with the first year in Bangalore and second year in Hyderabad, providing exposure to diverse industrial environments and networking opportunities.',
  '[
    {"semester": 1, "subjects": ["Statistical Decision Making-1", "Statistical Process Control (SPC)", "Research Methodology & Statistics-1", "Operations Research-1", "Total Quality Management", "Project Management", "Computer Applications"]},
    {"semester": 2, "subjects": ["Statistical Decision Making-2", "Advanced Statistical Process Control", "Research Methodology & Statistics-2", "Operations Research-2", "Multivariate Data Analysis", "Design of Experiments", "Quality Systems & ISO Standards"]},
    {"semester": 3, "subjects": ["Six Sigma Methodology", "Operations Research-3", "Regression Analysis & Forecasting", "Quality Audit & Assessment", "Industrial Experimentation", "Supply Chain Management", "Electives (Game Theory/Neural Networks)"]},
    {"semester": 4, "subjects": ["Master''s Dissertation", "Live Industry Project", "Seminar Presentations", "Internship", "Advanced Electives"]}
  ]'::jsonb,
  '[
    {"question": "How competitive is the MSQMS admission process?", "answer": "Highly competitive with only 15 seats available. The program attracts candidates from top engineering and science backgrounds across India."},
    {"question": "What makes MSQMS different from MBA programs?", "answer": "MSQMS focuses on quantitative methods and statistical analysis for quality management, while MBA programs have broader business focus. MSQMS provides deeper technical expertise."},
    {"question": "Are there internship opportunities during the program?", "answer": "Yes, students complete mandatory internships with leading companies. Internship stipends range from ₹1-2.5 lakhs for the duration."},
    {"question": "What are the career paths after MSQMS?", "answer": "Graduates work in quality management, business analytics, operations research, consulting, and pursue PhD programs at top institutions worldwide."},
    {"question": "Is the program suitable for working professionals?", "answer": "The program is full-time and residential, not suitable for working professionals. However, ISI offers sponsored candidate category for industry-nominated students."},
    {"question": "What is the success rate in placements?", "answer": "100% placement record with students receiving multiple offers. The small batch size ensures personalized career guidance and excellent placement support."}
  ]'::jsonb,
  '/images/isi-msqms.jpg',
  'isi-msqms-free',
  'isi-msqms-premium'
) ON CONFLICT DO NOTHING;

-- Add more sample exams for variety
INSERT INTO public.exams (name, description, short_description, established_year, location) VALUES
('CMI', 'Chennai Mathematical Institute - Excellence in Mathematics and Computer Science', 'Premier institute for Mathematics and Computer Science', 1989, 'Chennai, Tamil Nadu'),
('IIT JAM', 'Joint Admission Test for Masters - Gateway to IIT Masters Programs', 'Joint entrance for IIT M.Sc programs', 1976, 'Multiple IIT Campuses'),
('JNU', 'Jawaharlal Nehru University - Leading Social Sciences and Humanities', 'Top university for social sciences research', 1969, 'New Delhi'),
('BHU', 'Banaras Hindu University - Ancient wisdom meets modern education', 'One of India''s largest residential universities', 1916, 'Varanasi, Uttar Pradesh')
ON CONFLICT (name) DO NOTHING;
