-- Add sample data for CMI exam and MSDS course
INSERT INTO exams (
  id,
  name, 
  description,
  short_description,
  location,
  established_year,
  detailed_description,
  introduction,
  history,
  recognition,
  rankings,
  infrastructure,
  placements,
  global_collaborations,
  fees_scholarships,
  preparation_tips,
  why_choose,
  syllabus,
  campus,
  admission_procedure,
  exam_pattern,
  pyqs,
  cutoff_trends,
  short_notes,
  important_dates,
  eligibility_criteria,
  exam_centers,
  scholarships_stipends,
  recommended_books,
  campuses,
  faqs
) VALUES (
  gen_random_uuid(),
  'CMI',
  'Chennai Mathematical Institute - Premier Institute for Mathematics and Computer Science',
  'Chennai Mathematical Institute (CMI) is a leading research institute in mathematics, physics, and computer science.',
  'Chennai, Tamil Nadu',
  1989,
  'Chennai Mathematical Institute (CMI) is a research and education institute in Chennai, India. It was founded in 1989 by the SPIC Science Foundation, and offers undergraduate and postgraduate programs in mathematics, physics, and computer science. CMI is known for its rigorous academic programs and research excellence.',
  'CMI stands as a beacon of excellence in mathematical sciences and computer science, consistently producing world-class researchers and professionals.',
  'Founded in 1989 by the SPIC Science Foundation, CMI has established itself as a premier research institute. The institute has grown from a small research center to a world-renowned institution attracting brilliant minds from across the globe.',
  'CMI is recognized by the University Grants Commission (UGC) and is known for its exceptional research output and academic excellence.',
  'Consistently ranked among the top institutes in India for mathematics and computer science research. QS World University Rankings recognizes CMI among top research institutions.',
  'State-of-the-art computing facilities, well-equipped laboratories, extensive library with digital resources, high-speed internet connectivity, and modern classrooms with audio-visual aids.',
  'CMI graduates are highly sought after by top tech companies, research institutions, and universities worldwide. Many alumni pursue advanced research degrees at prestigious international universities.',
  'Strong collaborations with leading international universities and research institutions. Regular exchange programs with institutions in Europe, USA, and Asia.',
  'Merit-based scholarships available for deserving students. Fee structure is reasonable considering the quality of education. Financial assistance provided for economically disadvantaged students.',
  'Focus on building strong mathematical foundation, practice problem-solving regularly, participate in mathematical olympiads, and develop analytical thinking skills.',
  'Exceptional faculty-student ratio, world-class research environment, strong industry connections, and excellent placement record make CMI the ideal choice for aspiring mathematicians and computer scientists.',
  'Comprehensive curriculum covering core mathematics, applied mathematics, computer science fundamentals, and interdisciplinary subjects.',
  'Beautiful campus in Chennai with modern facilities, hostels, dining facilities, sports complex, and recreational areas.',
  'Admission through CMI Entrance Examination followed by interview. Application process typically starts in March-April each year.',
  'Written examination covering mathematics, physics, and logical reasoning. Interview round for shortlisted candidates focusing on problem-solving abilities.',
  'Previous years question papers available for practice. Focus on mathematical concepts, problem-solving techniques, and logical reasoning.',
  'Cut-off varies each year based on performance. Generally, top 1-2% performers get selected for the program.',
  'Comprehensive study materials available covering all topics. Focus on conceptual understanding rather than rote learning.',
  'Important Dates: Application opens in March, Entrance exam in May, Results in June, Admission process completes by July.',
  'Candidates must have completed 10+2 with Mathematics as a subject. Minimum 60% marks required in qualifying examination.',
  'Entrance examination conducted in major cities across India including Chennai, Mumbai, Delhi, Kolkata, Bangalore, and Hyderabad.',
  'Merit scholarships, need-based financial assistance, and special scholarships for students from rural areas and economically weaker sections.',
  'Higher Mathematics by Dasgupta, Introduction to Algorithms by Cormen, Mathematical Analysis by Rudin, and other standard mathematics and computer science textbooks.',
  '[{"name": "Main Campus", "location": "Chennai, Tamil Nadu", "description": "Primary campus with all major facilities"}]',
  '[{"question": "What is the duration of the program?", "answer": "The undergraduate program is of 3 years duration."}, {"question": "Is there any age limit?", "answer": "No, there is no upper age limit for admission."}, {"question": "What are the career prospects?", "answer": "Graduates can pursue research, join tech companies, or continue higher studies."}]'
) ON CONFLICT DO NOTHING;

-- Get the CMI exam ID for course insertion
INSERT INTO courses (
  id,
  exam_id,
  name,
  description,
  duration,
  intake_capacity,
  average_package,
  degree_type,
  course_overview,
  entrance_exam_details,
  placement_statistics,
  exam_pattern,
  skills_learning_outcomes,
  admission_procedure,
  preparation_strategy,
  syllabus,
  notes,
  short_notes,
  chapter_wise_questions,
  full_length_mocks,
  course_curriculum,
  projects_assignments,
  day_in_life,
  campus_life,
  alumni_stories,
  global_exposure,
  course_comparison,
  quick_facts,
  freemium_group,
  premium_group,
  is_calculator,
  is_parts,
  test_parts
) VALUES (
  gen_random_uuid(),
  (SELECT id FROM exams WHERE name = 'CMI' LIMIT 1),
  'Mathematics and Computer Science (Integrated)',
  'Integrated program combining mathematics and computer science with research opportunities',
  '3 Years',
  '50',
  '15-20 LPA',
  'Bachelor''s',
  'The Mathematics and Computer Science program at CMI offers a unique blend of theoretical mathematics and practical computer science. Students gain deep understanding of mathematical concepts while developing strong programming and algorithmic skills.',
  'Admission through CMI Entrance Examination covering mathematics, logical reasoning, and basic computer science concepts. Interview round focuses on problem-solving abilities and mathematical aptitude.',
  '100% placement rate with average package of 15-20 LPA. Top recruiters include Google, Microsoft, Facebook, Amazon, Goldman Sachs, and leading research institutions.',
  'Written test with sections on Mathematics (50%), Logical Reasoning (30%), and Computer Science basics (20%). Duration: 3 hours, 100 questions.',
  'Strong analytical and problem-solving skills, Mathematical modeling, Algorithm design and analysis, Programming proficiency, Research methodology, Critical thinking.',
  'Online application followed by entrance examination. Shortlisted candidates called for interview. Final selection based on combined performance.',
  'Build strong foundation in mathematics, practice logical reasoning, familiarize with basic programming concepts, solve previous years papers.',
  'Core Mathematics: Calculus, Linear Algebra, Abstract Algebra, Real Analysis, Discrete Mathematics. Computer Science: Programming, Data Structures, Algorithms, Database Systems, Machine Learning.',
  'Comprehensive study materials covering all subjects with detailed explanations and solved examples.',
  'Concise notes for quick revision covering important formulas, theorems, and concepts.',
  'Topic-wise practice questions with detailed solutions for thorough preparation.',
  'Complete mock tests simulating actual entrance examination pattern and difficulty level.',
  'Semester 1-2: Foundation Mathematics and Programming, Semester 3-4: Advanced Mathematics and Algorithms, Semester 5-6: Specialization and Research Project.',
  'Individual and group projects, Research internships, Industry collaborations, International exchange programs.',
  'Early morning lectures, Problem-solving sessions, Group discussions, Research meetings, Evening sports and cultural activities.',
  'Vibrant campus life with cultural festivals, sports competitions, technical symposiums, guest lectures, and social activities.',
  'Alumni working in top tech companies worldwide, Successful entrepreneurs, Renowned researchers and academicians, Award-winning professionals.',
  'International exchange programs, Collaborative research projects, Global conferences and workshops, Industry partnerships.',
  'Unique integrated curriculum, Strong research focus, Excellent faculty-student ratio, Outstanding placement record compared to other programs.',
  'Founded: 1989, Campus: Chennai, Programs: 3, Research Labs: 15, Faculty: 45, International Collaborations: 25+',
  'mathematics_basic',
  'mathematics_advanced',
  true,
  false,
  NULL
) ON CONFLICT DO NOTHING;